class CreatePictures < ActiveRecord::Migration 
	# generated by rails through command in iterm
  def up
  	create_table :pictures do |t|
  		t.string :artist
  		t.string :title
  		t.string :url
  	end
  end

  def down
  	drop_table :pictures 
  end
end

